ERROR - test_sample - Exception in test case set up: `teleport` is not created in `network:0`. Reason: error_code: `-5` error_log: `No such variable name2
Bad value: name
`

Test case execution time is 4.18 seconds
